# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Parse-Win32Registry
version:      0.25
version_from: lib/Parse/Win32Registry.pm
installdirs:  site
requires:
    Carp:                          0
    Encode:                        0
    Test::More:                    0
    Time::Local:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
