--- #YAML:1.0
name:               Parse-Win32Registry
version:            1.0
abstract:           Parse Windows Registry Files
author:
    - James Macfarlane
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:            0
    Data::Dumper:    0
    Encode:          0
    File::Basename:  0
    Test::More:      0
    Time::Local:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
